### ISSUE TITLE
Player model rotates around the X and Z axis.

### ISSUE THREAD

**Issue by ChristianStiehl** [Athosvk/Confus#39]
Once the server is up, we should only communicate the Y rotation of all players to other players. If X and Z rotation does not influence collision then this is a non-issue.

**Comment by Athosvk** [comment]
We should simply prevent the player model from rotating in the first place. This goes horribly wrong if you want to do any form of client side prediction regarding the storing of collision events.

**Comment by Athosvk** [comment]
Oops, done already
